name: Node.js CI

on:
  push:
    branches:
      - master
      - develop
      - release/*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Node.js CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Yarn
        uses: bahmutov/npm-install@v1.1.0
      - name: Test
        run: yarn test
